Drop setuptools-markdown
Stop using setuptools-markdown which is no longer maintained and
doesn't work anymore. Instead use the long_description_content_type
variable (see [0]) to indicate that the given long_description is in
markdown format.

This fixes:

AttributeError: module 'pypandoc' has no attribute 'convert'

[0] https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/

Fixes #112